language: python
python:
- "3.6"

addons:
 chrome: stable

env:
 - PATH=$PATH:/usr/lib/chromium-browser/ DISPLAY=:99.0 CHROME_BIN=/usr/bin/google-chrome

install:
- pip install -r requirements.txt
- pip install selenium
- pip install mock
- pip install pytest
- pip freeze > requirements.txt
#commands to run tests
script:
- pytest
